name: Sync to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        run: |
          git config --global user.email "kira.iovenko@gmail.com"
          git config --global user.name "kira-iovenko"
          # Clone with token for authentication
          git clone https://kiovenko:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/kiovenko/scheduleBot_UI hf_space
          rsync -av --exclude='.git' ./ hf_space/
          cd hf_space
          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"
          git push origin main
