name: Sync Frontend + Backend to HF Docker Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync repo to new HF Docker Space
        env:
          HF_TOKEN: ${{ secrets.HF_SECRET }}
        run: |
          #Clone HF Space repo
          git clone https://kiovenko:$HF_TOKEN@huggingface.co/spaces/kiovenko/ScheduleBot hf_space

          #Enter the HF Space repo
          cd hf_space

          #Configure Git identity (must be here, after cd)          
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          #Remove old files except .git
          find . -maxdepth 1 ! -name ".git" ! -name "." -exec rm -rf {} +

          #Copy only needed files
          cp ../Dockerfile ../app.py ../requirements.txt ../README.md -t .
          cp -R ../frontend ./frontend

          #Stage all changes
          git add -A

          #Commit if there are changes
          git diff --cached --quiet || git commit -m "Sync repo for Docker Space"

          #Push to HF
          git push origin main --force
