name: Sync Frontend to Hugging Face

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout your GitHub repository
      - uses: actions/checkout@v3

      # Sync frontend to Hugging Face Space
      - name: Push Frontend to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_SECRET }}
        run: |
          # Clone the Hugging Face Space repo
          git clone https://kiovenko:$HF_TOKEN@huggingface.co/spaces/kiovenko/scheduleBot_UI hf_space

          # Copy frontend files to root of hf_space
          rsync -av --delete ./frontend/ hf_space/

          # Enter the Space repo
          cd hf_space

          # Configure git user
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          # Stage and commit changes
          git add -A
          git commit -m "Sync frontend from GitHub" || echo "No changes to commit"

          # Push to Hugging Face Space
          git push origin main --force
